steps:

- name: 'maven:3.9.6-eclipse-temurin-17'
  entrypoint: 'mvn'
  args:
    - clean
    - package

- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/transaction-repo/transaction-api:$SHORT_SHA'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/transaction-repo/transaction-api:$SHORT_SHA'

images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/transaction-repo/transaction-api:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY